export const environment = {
  installedInstances: ["default", "asean", "kh", "kh-moc", "jp", "sg"],
  env: "localhost",
  appUrl: "http://localhost:4200",
  backendUrl: "https://api.wipopublish-webapp-dev.ipobs.dev.web1.wipo.int",
};

export const configuration = {
  default: {
    name: "WIPO IPAS Central",
    logo: "/assets/images/wipo-logo.png",
    availableLangs: ["ar", "en", "fr", "id", "jp", "kh", "ms", "vi"],
    defaultLanguage: "en",
    defaultLandingModule: "dashboard",
  },
  asean: {
    name: "ASEAN",
    logo: "/assets/images/asean-logo.png",
    availableLangs: ["ar", "en", "fr", "id", "jp", "kh", "ms", "vi"],
    defaultLanguage: "fr",
    defaultLandingModule: "dashboard",
    supportedLanguages: ["en", "fr", "ar", "id", "jp", "kh", "ms", "vi"],
  },
  "kh-moc": {
    name: "KH MOC",
    logo: "/assets/images/kh-moc-logo.png",
    availableLangs: ["ar", "en", "fr", "id", "jp", "kh", "ms", "vi"],
    defaultLanguage: "fr",
    defaultLandingModule: "dashboard",
  },
  kh: {
    name: "KH",
    logo: "/assets/images/kh-logo.png",
    availableLangs: ["ar", "en", "fr", "id", "jp", "kh", "ms", "vi"],
    defaultLanguage: "fr",
    defaultLandingModule: "dashboard",
  },

  // Additional WIPO offices
  au: {
    name: "IP Australia",
    logo: "/assets/images/au-logo.png",
    availableLangs: ["en"],
    defaultLanguage: "en",
    defaultLandingModule: "dashboard",
  },
  br: {
    name: "INPI Brazil",
    logo: "/assets/images/br-logo.png",
    availableLangs: ["en", "pt"],
    defaultLanguage: "pt",
    defaultLandingModule: "dashboard",
  },
  ca: {
    name: "CIPO Canada",
    logo: "/assets/images/ca-logo.png",
    availableLangs: ["en", "fr"],
    defaultLanguage: "en",
    defaultLandingModule: "dashboard",
  },
  cn: {
    name: "CNIPA China",
    logo: "/assets/images/cn-logo.png",
    availableLangs: ["en", "zh"],
    defaultLanguage: "zh",
    defaultLandingModule: "dashboard",
  },
  ep: {
    name: "EPO",
    logo: "/assets/images/ep-logo.png",
    availableLangs: ["en", "fr", "de"],
    defaultLanguage: "en",
    defaultLandingModule: "dashboard",
  },
  gb: {
    name: "UK IPO",
    logo: "/assets/images/gb-logo.png",
    availableLangs: ["en"],
    defaultLanguage: "en",
    defaultLandingModule: "dashboard",
  },
  in: {
    name: "IP India",
    logo: "/assets/images/in-logo.png",
    availableLangs: ["en", "hi"],
    defaultLanguage: "en",
    defaultLandingModule: "dashboard",
  },
  jp: {
    name: "JPO Japan",
    logo: "/assets/images/jp-logo.png",
    availableLangs: ["en", "jp"],
    defaultLanguage: "jp",
    defaultLandingModule: "dashboard",
  },
  kr: {
    name: "KIPO Korea",
    logo: "/assets/images/kr-logo.png",
    availableLangs: ["en", "ko"],
    defaultLanguage: "ko",
    defaultLandingModule: "dashboard",
  },
  mx: {
    name: "IMPI Mexico",
    logo: "/assets/images/mx-logo.png",
    availableLangs: ["en", "es"],
    defaultLanguage: "es",
    defaultLandingModule: "dashboard",
  },
  ph: {
    name: "IPOPHL Philippines",
    logo: "/assets/images/ph-logo.png",
    availableLangs: ["en", "fil"],
    defaultLanguage: "en",
    defaultLandingModule: "dashboard",
  },
  sg: {
    name: "IPOS Singapore",
    logo: "/assets/images/sg-logo.png",
    availableLangs: ["en", "zh", "ms", "ta"],
    defaultLanguage: "en",
    defaultLandingModule: "dashboard",
  },
  th: {
    name: "DIP Thailand",
    logo: "/assets/images/th-logo.png",
    availableLangs: ["en", "th"],
    defaultLanguage: "th",
    defaultLandingModule: "dashboard",
  },
  us: {
    name: "USPTO",
    logo: "/assets/images/us-logo.png",
    availableLangs: ["en"],
    defaultLanguage: "en",
    defaultLandingModule: "dashboard",
  },
  vn: {
    name: "IP Vietnam",
    logo: "/assets/images/vn-logo.png",
    availableLangs: ["en", "vi"],
    defaultLanguage: "vi",
    defaultLandingModule: "dashboard",
  },
  za: {
    name: "CIPC South Africa",
    logo: "/assets/images/za-logo.png",
    availableLangs: ["en", "af", "zu", "xh"],
    defaultLanguage: "en",
    defaultLandingModule: "dashboard",
  },

  sa: {
    name: "SAIP Saudi Arabia",
    logo: "/assets/images/sa-logo.png",
    availableLangs: ["en", "ar"],
    defaultLanguage: "ar",
    defaultLandingModule: "dashboard",
  },

  vc: {
    name: "CIPO St. Vincent & Grenadines",
    logo: "/assets/images/vc-logo.png",
    availableLangs: ["en"],
    defaultLanguage: "en",
    defaultLandingModule: "dashboard",
  },
};
