export const environment = {
  installedInstances: [
    'default',
    'xx',
    'asean',
    'kh',
    'kh-moc',
    'jp',
    'sg',
    'bt',
    'vc',
    'cv',
  ],
  env: 'localhost',
  appUrl: 'http://localhost:4200',
  configUrl: '/services/offices',
  backendUrl: '/services/users',
  dataServicesApi: '/data-services/v1/shared-packages',
  feesConditionsUrl: '/services/fees/v1/conditions/all/application',
  authApi: 'https://auth.iims.ipobs.dev.web1.wipo.int/oauth2/token',
  authApiUsername: '160dg69c2ekjev3fh80msmome9',
  authApiPassword: '1llb7572v5595lmkeb25ouv57mn435iumnr05vrmeo0oo19me43b',
  cognito: {
    region: 'eu-central-1',
    userPoolId: 'eu-central-1_aIn5Yy5c5',
    clientId: '7vp4nvcrpsttatcg8lf7cds7g4',
    authority: 'auth.iims.ipobs.dev.web1.wipo.int',
    redirectUrl: 'https://localhost:4200/auth-callback',
    postLogoutRedirectUri: 'https://localhost:4200/logged-out',
    scope:
      'aws.cognito.signin.user.admin email im-api/im-access openid profile wipopublish-api/data-quality-access',
    responseType: 'code',
  },
};

export const configuration = {
  xx: {
    name: 'WIPO IP Support Office',
    officeCode: 'xx',
    logo: '/assets/images/wipo-logo.png',
    availableLangs: ['ar', 'en', 'fr', 'id', 'jp', 'kh', 'ms', 'vi'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
  },
  default: {
    name: 'WIPO IPAS Central',
    officeCode: 'default',
    logo: '/assets/images/wipo-logo.png',
    availableLangs: ['ar', 'en', 'fr', 'id', 'jp', 'kh', 'ms', 'vi'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
  },
  asean: {
    name: 'ASEAN',
    officeCode: 'asean',
    logo: '/assets/images/asean-logo.png',
    availableLangs: ['ar', 'en', 'fr', 'id', 'jp', 'kh', 'ms', 'vi'],
    defaultLanguage: 'fr',
    defaultLandingModule: 'dashboard',
  },
  vc: {
    name: 'CIPO St. Vincent & Grenadines',
    officeCode: 'vc',
    logo: '/assets/images/vc-logo.png',
    availableLangs: ['en', 'fr', 'id', 'jp', 'ar'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
  },
  'kh-moc': {
    name: 'KH MOC',
    officeCode: 'kh-moc',
    logo: '/assets/images/kh-moc-logo.png',
    availableLangs: ['ar', 'en', 'fr', 'id', 'jp', 'kh', 'ms', 'vi'],
    defaultLanguage: 'fr',
    defaultLandingModule: 'dashboard',
  },
  kh: {
    name: 'KH',
    officeCode: 'kh',
    logo: '/assets/images/kh-logo.png',
    availableLangs: ['ar', 'en', 'fr', 'id', 'jp', 'kh', 'ms', 'vi'],
    defaultLanguage: 'fr',
    defaultLandingModule: 'dashboard',
  },
  bt: {
    name: 'Ministry of Industry,<br/> Commerce and Employment <br/> (MoICE)',
    officeCode: 'bt',
    logo: '/assets/images/bt-logo.jpeg',
    availableLangs: ['ar', 'en', 'fr', 'id', 'jp', 'kh', 'ms', 'vi'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
  },
  // Additional WIPO offices
  au: {
    name: 'IP Australia',
    officeCode: 'au',
    logo: '/assets/images/au-logo.png',
    availableLangs: ['en'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
  },
  br: {
    name: 'INPI Brazil',
    officeCode: 'br',
    logo: '/assets/images/br-logo.png',
    availableLangs: ['en', 'pt'],
    defaultLanguage: 'pt',
    defaultLandingModule: 'dashboard',
  },
  ca: {
    name: 'CIPO Canada',
    officeCode: 'ca',
    logo: '/assets/images/ca-logo.png',
    availableLangs: ['en', 'fr'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
  },
  cn: {
    name: 'CNIPA China',
    officeCode: 'cn',
    logo: '/assets/images/cn-logo.png',
    availableLangs: ['en', 'zh'],
    defaultLanguage: 'zh',
    defaultLandingModule: 'dashboard',
  },
  jp: {
    name: 'JPO Japan',
    officeCode: 'jp',
    logo: '/assets/images/jp-logo.png',
    availableLangs: ['en', 'jp'],
    defaultLanguage: 'jp',
    defaultLandingModule: 'dashboard',
  },
  sg: {
    name: 'IPOS Singapore',
    officeCode: 'sg',
    logo: '/assets/images/sg-logo.png',
    availableLangs: ['en', 'zh', 'ms', 'ta'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
  },
  th: {
    name: 'DIP Thailand',
    officeCode: 'th',
    logo: '/assets/images/th-logo.png',
    availableLangs: ['en', 'th'],
    defaultLanguage: 'th',
    defaultLandingModule: 'dashboard',
  },
  vn: {
    name: 'IP Vietnam',
    officeCode: 'vn',
    logo: '/assets/images/vn-logo.png',
    availableLangs: ['en', 'vi'],
    defaultLanguage: 'vi',
    defaultLandingModule: 'dashboard',
  },
  sa: {
    name: 'SAIP Saudi Arabia',
    officeCode: 'sa',
    logo: '/assets/images/sa-logo.png',
    availableLangs: ['en', 'ar'],
    defaultLanguage: 'ar',
    defaultLandingModule: 'dashboard',
  },
  cv: {
    name: 'IGQPI - Instituto de Gestão da Qualidade e da \n Propriedade Intelectual',
    officeCode: 'cv',
    logo: '/assets/images/cv-logo.jpeg',
    availableLangs: ['en', 'fr'],
    defaultLanguage: 'fr',
    defaultLandingModule: 'dashboard',
  },
};
