export const environment = {
  installedInstances: [
    'default',
    'xx',
    'asean',
    'kh',
    'kh-moc',
    'jp',
    'sg',
    'bn',
    'br',
    'bt',
    'la',
    'vc',
    'cv',
    'vn',
    'in',
    'ph',
    'my',
    'th',
  ],
  env: 'awsdev',
  efillingUrl: 'https://ipoffice-efiling-dev.ipobs.dev.web1.wipo.int/sign-in',
  appUrl: 'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int',
  distributionRulesPath: 'data-services/v1/distribution-exclusion',
  dataServicesApi:
    'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/data-services/v1/shared-packages',
  feesConditionsUrl:
    'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/services/v1/fees',
  documentOriginsUrl:
    'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/services/offices/configurations/document-origins',
  authApi: 'https://auth.iims.ipobs.dev.web1.wipo.int/oauth2/token',
  authApiUsername: '160dg69c2ekjev3fh80msmome9',
  authApiPassword: '1llb7572v5595lmkeb25ouv57mn435iumnr05vrmeo0oo19me43b',
  configUrl:
    'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/services/offices',
  backendUrl:
    'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/services/users',
  cognito: {
    region: 'eu-central-1',
    userPoolId: 'eu-central-1_aIn5Yy5c5',
    clientId: '7vp4nvcrpsttatcg8lf7cds7g4',
    authority: 'auth.iims.ipobs.dev.web1.wipo.int',
    redirectUrl:
      'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/auth-callback',
    postLogoutRedirectUri:
      'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/logged-out',
    scope:
      'aws.cognito.signin.user.admin email im-api/im-access openid profile',
    responseType: 'code',
  },
};

export const configuration = {
  bn: {
    name: 'Intellectual Property of BRUNEI DARUSSALAM',
    officeCode: 'bn',
    logo: '/assets/images/bn-logo.png',
    availableLangs: ['en'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
  },
  br: {
    name: ' Instituto Nacional da Propriedade Industrial INPI',
    officeCode: 'br',
    logo: '/assets/images/br-logo.png',
    availableLangs: ['en', 'pt'],
    defaultLanguage: 'pt',
    defaultLandingModule: 'dashboard',
    efilingEnabled: false,
    hideTitle: true,
  },
  bt: {
    name: 'Ministry of Industry,Commerce and Employment (MoICE)',
    officeCode: 'bt',
    logo: '/assets/images/bt-logo.jpeg',
    availableLangs: ['ar', 'en', 'fr', 'id', 'jp', 'kh', 'ms', 'vi'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
  },
  cv: {
    name: 'IGQPI - Instituto de Gestão da Qualidade e da \n Propriedade Intelectual',
    officeCode: 'cv',
    logo: '/assets/images/cv-logo.jpeg',
    availableLangs: ['en', 'fr'],
    defaultLanguage: 'fr',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: false,
  },
  in: {
    name: 'IP India',
    officeCode: 'in',
    logo: '/assets/images/in-logo.png',
    availableLangs: ['en'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: false,
    hideTitle: true,
  },
  'kh-moc': {
    name: 'KH MOC',
    officeCode: 'kh-moc',
    logo: '/assets/images/kh-moc-logo.png',
    availableLangs: ['ar', 'en', 'fr', 'id', 'jp', 'kh', 'ms', 'vi'],
    defaultLanguage: 'fr',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
  },
  la: {
    name: 'DIP Lao PDR',
    officeCode: 'la',
    logo: '/assets/images/la-logo.png',
    availableLangs: ['en'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
  },
  my: {
    name: 'Intellectual Property Coorporation of Malaysia',
    officeCode: 'my',
    logo: '/assets/images/my-logo.png',
    availableLangs: ['en'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
  },
  ph: {
    name: 'Intellectual Property of the Philippines',
    officeCode: 'ph',
    logo: '/assets/images/ph-logo.png',
    availableLangs: ['en'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
  },
  sg: {
    name: 'IPOS Singapore',
    officeCode: 'sg',
    logo: '/assets/images/sg-logo.png',
    availableLangs: ['en', 'zh', 'ms', 'ta'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: false,
    hideTitle: true,
  },
  th: {
    name: 'DIP Thailand',
    officeCode: 'th',
    logo: '/assets/images/th-logo.png',
    availableLangs: ['en', 'th'],
    defaultLanguage: 'th',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
  },
  vc: {
    name: 'CIPO St. Vincent & Grenadines',
    officeCode: 'vc',
    logo: '/assets/images/vc-logo.png',
    availableLangs: ['en', 'fr', 'id', 'jp', 'ar'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: false,
  },
  vn: {
    name: 'IP Vietnam',
    officeCode: 'vn',
    logo: '/assets/images/vn-logo.png',
    availableLangs: ['en', 'vi'],
    defaultLanguage: 'vi',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
  },
  xx: {
    name: 'WIPO IP Office Support Platform',
    officeCode: 'xx',
    logo: '/assets/images/wipo-logo.png',
    availableLangs: ['ar', 'en', 'fr', 'id', 'jp', 'kh', 'ms', 'vi'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: false,
  },
};
