export const environment = {
  installedInstances: [
    'default',
    'xx',
    'asean',
    'kh',
    'kh-moc',
    'jp',
    'sg',
    'bn',
    'br',
    'bt',
    'la',
    'vc',
    'cv',
    'vn',
    'in',
    'ph',
    'my',
    'th',
  ],
  env: 'awsdev',
  efillingUrl: 'https://ipoffice-efiling-dev.ipobs.dev.web1.wipo.int/sign-in',
  enableLogging: false,
  appUrl: 'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int',
  distributionRulesPath: 'data-sharing/v1/data-distributions',
  recipientsPath: 'data-sharing/v1/appClient',
  dataServicesApi:
    'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/data-services/v1/packages',
  authorityServicesApi: 'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/data-services/v1/authority-files',
  feesConditionsUrl:
    'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/services/v1/fees',
  documentOriginsUrl:
    'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/services/offices/configurations/document-origins',
  authApi: 'https://auth.iims.ipobs.dev.web1.wipo.int/oauth2/token',
  authApiUsername: '160dg69c2ekjev3fh80msmome9',
  authApiPassword: '1llb7572v5595lmkeb25ouv57mn435iumnr05vrmeo0oo19me43b',
  configUrl:
    'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/services/offices',
  backendUrl:
    'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/services/users',
  similaritySearchApi:
    'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/search/registry',
  similaritySearchImage:
    'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/search/image',
  similarityTextToImage:
    'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/search/text-to-image',
  analyzeApi: '/analyze',
  cognito: {
    region: 'eu-central-1',
    userPoolId: 'eu-central-1_aIn5Yy5c5',
    clientId: '7vp4nvcrpsttatcg8lf7cds7g4',
    authority: 'auth.iims.ipobs.dev.web1.wipo.int',
    redirectUrl:
      'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/auth-callback',
    postLogoutRedirectUri:
      'https://ipas-ipoffice-dev.ipobs.dev.web1.wipo.int/logged-out',
    scope:
      'aws.cognito.signin.user.admin email im-api/im-access openid profile wipopublish-api/data-quality-access data-services/internal-access data-services/public-access data-sharing/admin-access',
    responseType: 'code',
  },
};

export const configuration = {
  bn: {
    name: 'Intellectual Property of BRUNEI DARUSSALAM',
    officeCode: 'bn',
    ipasDatabase: 'ipas-bn',
    logo: '/assets/images/bn-logo.png',
    availableLangs: ['en'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
    ipTypes: ['patent', 'trademark', 'designs'],
    eventCodes: ['A10', 'B10', 'F10', 'H10', 'N10', 'Q10', 'U10', 'W10'],
    documentTypes: {
      patent: ['ABT', 'PTA', 'PTD', 'SME', 'RAM'],
      design: [],
      trademark: [],
    },
  },
  br: {
    name: ' Instituto Nacional da Propriedade Industrial INPI',
    officeCode: 'br',
    ipasDatabase: 'ipas-br',
    logo: '/assets/images/br-logo.png',
    availableLangs: ['en', 'pt'],
    defaultLanguage: 'pt',
    defaultLandingModule: 'dashboard',
    efilingEnabled: false,
    hideTitle: true,

    ipTypes: [
      'patent',
      'trademark',
      'copyright',
      'design',
      'geographical indication',
    ],
    eventCodes: ['A10', 'B10', 'F10', 'H10', 'N10', 'Q10', 'U10', 'W10'],
    documentTypes: {
      patent: ['ABT', 'PTA', 'PTD', 'SME', 'RAM'],
      design: [],
      trademark: [],
    },
  },
  bt: {
    name: 'Ministry of Industry,Commerce and Employment (MoICE)',
    officeCode: 'bt',
    ipasDatabase: 'ipas-bt',
    logo: '/assets/images/bt-logo.jpeg',
    availableLangs: ['ar', 'en', 'fr', 'id', 'jp', 'kh', 'ms', 'vi'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
    ipTypes: [
      'patent',
      'trademark',
      'copyright',
      'design',
      'geographical indication',
    ],
    eventCodes: ['A10', 'B10', 'F10', 'H10', 'N10', 'Q10', 'U10', 'W10'],
    documentTypes: {
      patent: ['ABT', 'PTA', 'PTD', 'SME', 'RAM'],
      design: [],
      trademark: [],
    },
  },
  cv: {
    name: 'IGQPI - Instituto de Gestão da Qualidade e da \n Propriedade Intelectual',
    officeCode: 'cv',
    ipasDatabase: 'ipas-cv',
    logo: '/assets/images/cv-logo.jpeg',
    availableLangs: ['en', 'fr'],
    defaultLanguage: 'fr',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: false,
    ipTypes: [
      'patent',
      'trademark',
      'copyright',
      'design',
      'geographical indication',
    ],
    eventCodes: ['A10', 'B10', 'F10', 'H10', 'N10', 'Q10', 'U10', 'W10'],
    documentTypes: {
      patent: ['ABT', 'PTA', 'PTD', 'SME', 'RAM'],
      design: [],
      trademark: [],
    },
  },
  in: {
    name: 'IP India',
    officeCode: 'in',
    ipasDatabase: 'ipas-in',
    logo: '/assets/images/in-logo.png',
    availableLangs: ['en'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: false,
    hideTitle: true,
    ipTypes: [
      'patent',
      'trademark',
      'copyright',
      'design',
      'geographical indication',
    ],
    eventCodes: ['A10', 'B10', 'F10', 'H10', 'N10', 'Q10', 'U10', 'W10'],
    documentTypes: {
      patent: ['ABT', 'PTA', 'PTD', 'SME', 'RAM'],
      design: [],
      trademark: [],
    },
  },
  'kh-moc': {
    name: 'KH MOC',
    officeCode: 'kh-moc',
    ipasDatabase: 'ipas-kh-moc',
    logo: '/assets/images/kh-moc-logo.png',
    availableLangs: ['ar', 'en', 'fr', 'id', 'jp', 'kh', 'ms', 'vi'],
    defaultLanguage: 'fr',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
    ipTypes: [
      'patent',
      'trademark',
      'copyright',
      'design',
      'geographical indication',
    ],
    eventCodes: ['A10', 'B10', 'F10', 'H10', 'N10', 'Q10', 'U10', 'W10'],
    documentTypes: {
      patent: ['ABT', 'PTA', 'PTD', 'SME', 'RAM'],
      design: [],
      trademark: [],
    },
  },
  la: {
    name: 'DIP Lao PDR',
    officeCode: 'la',
    ipasDatabase: 'ipas-la',
    logo: '/assets/images/la-logo.png',
    availableLangs: ['en'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
    ipTypes: [
      'patent',
      'trademark',
      'copyright',
      'design',
      'geographical indication',
    ],
    eventCodes: ['A10', 'B10', 'F10', 'H10', 'N10', 'Q10', 'U10', 'W10'],
    documentTypes: {
      patent: ['ABT', 'PTA', 'PTD', 'SME', 'RAM'],
      design: [],
      trademark: [],
    },
  },
  my: {
    name: 'Intellectual Property Coorporation of Malaysia',
    officeCode: 'my',
    logo: '/assets/images/my-logo.png',
    availableLangs: ['en'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
    ipTypes: [
      'patent',
      'trademark',
      'copyright',
      'design',
      'geographical indication',
    ],
    eventCodes: ['A10', 'B10', 'F10', 'H10', 'N10', 'Q10', 'U10', 'W10'],
    documentTypes: {
      patent: ['ABT', 'PTA', 'PTD', 'SME', 'RAM'],
      design: [],
      trademark: [],
    },
  },
  ph: {
    name: 'Intellectual Property of the Philippines',
    officeCode: 'ph',
    ipasDatabase: 'ipas-ph',
    logo: '/assets/images/ph-logo.png',
    availableLangs: ['en'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
    ipTypes: [
      'patent',
      'trademark',
      'copyright',
      'design',
      'geographical indication',
    ],
    eventCodes: ['A10', 'B10', 'F10', 'H10', 'N10', 'Q10', 'U10', 'W10'],
    documentTypes: {
      patent: ['ABT', 'PTA', 'PTD', 'SME', 'RAM'],
      design: [],
      trademark: [],
    },
  },
  sg: {
    name: 'IPOS Singapore',
    officeCode: 'sg',
    logo: '/assets/images/sg-logo.png',
    availableLangs: ['en', 'zh', 'ms', 'ta'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: false,
    hideTitle: true,
    ipTypes: [
      'patent',
      'trademark',
      'copyright',
      'design',
      'geographical indication',
    ],
    eventCodes: ['A10', 'B10', 'F10', 'H10', 'N10', 'Q10', 'U10', 'W10'],
    documentTypes: {
      patent: ['ABT', 'PTA', 'PTD', 'SME', 'RAM'],
      design: [],
      trademark: [],
    },
  },
  th: {
    name: 'DIP Thailand',
    officeCode: 'th',
    logo: '/assets/images/th-logo.png',
    availableLangs: ['en', 'th'],
    defaultLanguage: 'th',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
    ipTypes: [
      'patent',
      'trademark',
      'copyright',
      'design',
      'geographical indication',
    ],
    eventCodes: ['A10', 'B10', 'F10', 'H10', 'N10', 'Q10', 'U10', 'W10'],
    documentTypes: {
      patent: ['ABT', 'PTA', 'PTD', 'SME', 'RAM'],
      design: [],
      trademark: [],
    },
  },
  vc: {
    name: 'CIPO St. Vincent & Grenadines',
    officeCode: 'vc',
    ipasDatabase: 'ipas-vc',
    logo: '/assets/images/vc-logo.png',
    availableLangs: ['en', 'fr', 'id', 'jp', 'ar'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: false,
    ipTypes: [
      'patent',
      'trademark',
      'copyright',
      'design',
      'geographical indication',
    ],
    eventCodes: ['A10', 'B10', 'F10', 'H10', 'N10', 'Q10', 'U10', 'W10'],
    documentTypes: {
      patent: ['ABT', 'PTA', 'PTD', 'SME', 'RAM'],
      design: [],
      trademark: [],
    },
  },
  vn: {
    name: 'IP Vietnam',
    officeCode: 'vn',
    ipasDatabase: 'ipas-vn',
    logo: '/assets/images/vn-logo.png',
    availableLangs: ['en', 'vi'],
    defaultLanguage: 'vi',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: true,
    ipTypes: [
      'patent',
      'trademark',
      'copyright',
      'design',
      'geographical indication',
    ],
    eventCodes: ['A10', 'B10', 'F10', 'H10', 'N10', 'Q10', 'U10', 'W10'],
    documentTypes: {
      patent: ['ABT', 'PTA', 'PTD', 'SME', 'RAM'],
      design: [],
      trademark: [],
    },
  },
  xx: {
    name: 'WIPO IP Office Support Platform',
    officeCode: 'xx',
    ipasDatabase: 'ipas-central',
    logo: '/assets/images/wipo-logo.png',
    availableLangs: ['ar', 'en', 'fr', 'id', 'jp', 'kh', 'ms', 'vi'],
    defaultLanguage: 'en',
    defaultLandingModule: 'dashboard',
    efilingEnabled: true,
    hideTitle: false,
    ipTypes: [
      'patent',
      'trademark',
      'copyright',
      'design',
      'geographical indication',
    ],
    eventCodes: ['A10', 'B10', 'F10', 'H10', 'N10', 'Q10', 'U10', 'W10'],
    documentTypes: {
      patent: ['ABT', 'PTA', 'PTD', 'SME', 'RAM'],
      design: [],
      trademark: [],
    },
  },
};
