export const packagesData = [
  {
    id: '1',
    fileName: 'Patent_Combodia_Packages_2025_July_25_Package...',
    fileName_tooltip:
      'Patent_Combodia_Packages_2025_July_25_Package_Name_file1.zip',
    sharedDate: '2025-07-25',
    processedDate: '2025-07-25 17:30:05',
    status: 'In Progress',
    status_tooltip: 'Processed: 280 <br> Failed: 20',
    totalCount: '300',
    processedCount: '280',
    officeCode: 'KH',
    ipType: 'Patents',
    imageUrl: 'https://images.unsplash.com/photo-1604608619749-7dc84887834f',
  },
  {
    id: '2',
    fileName: 'file2.zip',
    sharedDate: '2024-12-12',
    processedDate: '2024-12-12 11:25:12',
    status: 'Processed',
    status_tooltip: 'Processed: 500 <br> Failed: 0',
    totalCount: '500',
    processedCount: '500',
    officeCode: 'KH',
    ipType: 'Trademarks',
    imageUrl: 'https://images.unsplash.com/photo-1672268931087-9384cca148d8',
  },
  {
    id: '3',
    fileName: 'file3.zip',
    sharedDate: '2025-01-02',
    processedDate: '2025-01-03 08:45:35',
    status: 'Processed',
    status_tooltip: 'Processed: 200 <br> Failed: 0',
    totalCount: '200',
    processedCount: '200',
    officeCode: 'SG',
    ipType: 'Patents',
    imageUrl: 'https://images.unsplash.com/photo-1604608619749-7dc84887834f',
  },
  {
    id: '4',
    fileName: 'file4.zip',
    sharedDate: '2025-07-13',
    processedDate: '2025-07-13 13:23:33',
    status: 'Partial',
    status_tooltip: 'Processed: 178 <br> Failed: 2',
    totalCount: '180',
    processedCount: '178',
    officeCode: 'SG',
    ipType: 'Industrial Designs',
    imageUrl: 'https://images.unsplash.com/photo-1672268931216-a2e1a6123c88',
  },
  {
    id: '5',
    fileName: 'file5.zip',
    sharedDate: '2023-01-25',
    processedDate: '2023-01-25 11:21:48',
    status: 'Failed',
    status_tooltip: 'Processed: 352 <br> Failed: 48',
    totalCount: '400',
    processedCount: '352',
    officeCode: 'LA',
    ipType: 'Trademarks',
    imageUrl: 'https://images.unsplash.com/photo-1672268931087-9384cca148d8',
  },
  {
    id: '6',
    fileName: 'file6.zip',
    sharedDate: '2025-09-03',
    processedDate: '2025-09-04 11:21:43',
    status: 'Partial',
    status_tooltip: 'Processed: 498 <br> Failed: 2',
    totalCount: '500',
    processedCount: '498',
    officeCode: 'SG',
    ipType: 'Industrial Designs',
    imageUrl: 'https://images.unsplash.com/photo-1672268931216-a2e1a6123c88',
  },
  {
    id: '7',
    fileName: 'file7.zip',
    sharedDate: '2025-09-01',
    processedDate: '2025-09-02 11:21:48',
    status: 'Failed',
    status_tooltip: 'Processed: 452 <br> Failed: 48',
    totalCount: '500',
    processedCount: '452',
    officeCode: 'LA',
    ipType: 'Trademarks',
    imageUrl: 'https://images.unsplash.com/photo-1672268931087-9384cca148d8',
  },
  {
    id: '8',
    fileName: 'file8.zip',
    sharedDate: '2025-09-04',
    processedDate: '2025-09-05 09:32:53',
    status: 'Partial',
    status_tooltip: 'Processed: 477 <br> Failed: 23',
    totalCount: '500',
    processedCount: '477',
    officeCode: 'SG',
    ipType: 'Patents',
    imageUrl: 'https://images.unsplash.com/photo-1672268931216-a2e1a6123c88',
  },
  {
    id: '9',
    fileName: 'file9.zip',
    sharedDate: '2025-09-05',
    processedDate: '2025-09-05 16:14:49',
    status: 'Failed',
    status_tooltip: 'Processed: 489 <br> Failed: 11',
    totalCount: '500',
    processedCount: '489',
    officeCode: 'LA',
    ipType: 'Trademarks',
    imageUrl: 'https://images.unsplash.com/photo-1672268931087-9384cca148d8',
  },
  {
    id: '10',
    fileName: 'Patents_Combodia_Packages_2025_September_04_Records...',
    fileName_tooltip:
      'Patents_Combodia_Packages_2025_September_04_Records_File_Folder_10.zip',
    sharedDate: '2025-09-04',
    processedDate: '2025-09-05 15:49:57',
    status: 'Partial',
    status_tooltip: 'Processed: 497 <br> Failed: 3',
    totalCount: '500',
    processedCount: '497',
    officeCode: 'KH',
    ipType: 'Patents',
    imageUrl: 'https://images.unsplash.com/photo-1672268931216-a2e1a6123c88',
  },
];

export const authorityData = [
  {
    id: '1',
    countryCode: 'KH',
    publicationNumber: '1/2018/00502603',
    publicationDate: '2025-07-02',
    kindCode: 'A1',
    exceptionCode: '',
    abstract: 'ABST-en',
    description: 'DESC-en',
    claims: 'CLMS-en',
    incomplete: 'true',
    image_tooltip: 'Abstract and Claims not available in full text data',
    image: '/assets/images/warning.png',
  },
  {
    id: '2',
    countryCode: 'KH',
    publicationNumber: '1/2018/00502645',
    publicationDate: '2025-06-07',
    kindCode: 'U3',
    exceptionCode: '',
    abstract: 'ABST-en',
    description: 'DESC-en',
    claims: 'CLMS-en',
    incomplete: 'false',
    incompleteFields: '',
  },
  {
    id: '3',
    countryCode: 'KH',
    publicationNumber: '1/2018/00502363',
    publicationDate: '2025-07-07',
    kindCode: 'U3',
    exceptionCode: '',
    abstract: 'ABST-en',
    description: 'DESC-en',
    claims: 'CLMS-en',
    incomplete: 'false',
    incompleteFields: '',
  },
  {
    id: '4',
    countryCode: 'KH',
    publicationNumber: '1/2018/00501004',
    publicationDate: '2025-07-05',
    kindCode: 'B1',
    exceptionCode: '',
    abstract: 'ABST-en',
    description: 'DESC-en',
    claims: 'CLMS-en',
    incomplete: 'true',
    image_tooltip: 'Claims not available in full text data',
    image: '/assets/images/warning.png',
  },
  {
    id: '5',
    countryCode: 'KH',
    publicationNumber: '1/2018/00502358',
    publicationDate: '2025-07-31',
    kindCode: 'A1',
    exceptionCode: '',
    abstract: 'ABST-en',
    description: 'DESC-en',
    claims: 'CLMS-en',
    incomplete: 'false',
    incompleteFields: '',
  },
];

export const renewalData = [
  {
    id: '1',
    ipType: 'patents',
    fileId: 'AP-P-2024-20092',
    expiryDate: '2025-10-21',
    renewalDueDate: '2025-11-20',
    expectedFee: '120 USD',
    fileSummary: 'Car Battery',
    fileOwners: 'John Paul, Peter King',
    notificationEmails: 'john.paul.1980@gmail.com',
    mailSentDate: '2025-08-20',
    selected: false,
    disabled: false,
  },
  {
    id: '2',
    ipType: 'patents',
    fileId: 'AP-P-2024-20183',
    expiryDate: '2025-11-19',
    renewalDueDate: '2025-12-18',
    expectedFee: '120 USD',
    fileSummary: 'Tea Maker',
    fileOwners: 'John Paul, Peter King',
    notificationEmails: 'john.paul.1980@gmail.com',
    mailSentDate: '2025-09-20',
    selected: false,
    disabled: false,
  },
  {
    id: '3',
    ipType: 'patents',
    fileId: 'AP-P-2024-100172',
    expiryDate: '2025-12-12',
    renewalDueDate: '2026-01-11',
    expectedFee: '120 USD',
    fileSummary: 'Remote Control',
    fileOwners: 'Jack Walter',
    notificationEmails: 'jack.walter.123@gmail.com',
    mailSentDate: '',
    selected: false,
    disabled: false,
  },
  {
    id: '4',
    ipType: 'trademarks',
    fileId: 'AT-T-2014-19221',
    expiryDate: '2025-08-21',
    renewalDueDate: '2025-09-20',
    expectedFee: '80 USD',
    fileSummary: 'ATP Panel',
    fileOwners: 'John Paul',
    notificationEmails: 'john.paul.1980@gmail.com',
    mailSentDate: '2025-08-20',
    selected: false,
    disabled: false,
  },
  {
    id: '5',
    ipType: 'trademarks',
    fileId: 'AT-T-2014-23567',
    expiryDate: '2025-06-13',
    renewalDueDate: '2025-17-12',
    expectedFee: '90 USD',
    fileSummary: 'AGS Partners',
    fileOwners: 'John Paul',
    notificationEmails: 'john.paul.1980@gmail.com',
    mailSentDate: '2025-08-20',
    selected: false,
    disabled: false,
  },
  {
    id: '6',
    ipType: 'trademarks',
    fileId: 'AT-T-2014-108472',
    expiryDate: '2025-10-13',
    renewalDueDate: '2025-11-12',
    expectedFee: '110 USD',
    fileSummary: 'PCL Labs',
    fileOwners: 'Peter Cairns',
    notificationEmails: 'petercairns_pcl@gmail.com',
    mailSentDate: '',
    selected: false,
    disabled: false,
  },
  {
    id: '7',
    ipType: 'designs',
    fileId: 'AD-D-2024-22331',
    expiryDate: '2025-12-28',
    renewalDueDate: '2026-02-27',
    expectedFee: '220 USD',
    fileSummary: 'Advanced Machine Drawing',
    fileOwners: 'George Carl',
    notificationEmails: 'gc_machines@gmail.com',
    mailSentDate: '',
    selected: false,
    disabled: false,
  },
  {
    id: '8',
    ipType: 'designs',
    fileId: 'AD-D-2024-10974',
    expiryDate: '2025-10-01',
    renewalDueDate: '2025-11-30',
    expectedFee: '180 USD',
    fileSummary: 'Automated cutter machine',
    fileOwners: 'Peter Parker',
    notificationEmails: 'online',
    mailSentDate: '2025-09-10',
    selected: false,
    disabled: true,
  },
  {
    id: '9',
    ipType: 'others',
    fileId: 'DOC-2024-23111',
    expiryDate: '2025-09-19',
    renewalDueDate: '2025-10-18',
    expectedFee: '70 USD',
    fileSummary: 'Definition docuemnt',
    fileOwners: 'Peter King',
    notificationEmails: 'paper',
    mailSentDate: '2025-09-10',
    selected: false,
    disabled: true,
  },
];

export const aripoNotificationsData = [
  {
    id: '1',
    batchId: 'AP_LR_REQUEST_20250624193716',
    fileId: 'AP-P-2022-14476',
    aripoSequence: '186660-14',
    fileSequence: '14',
    formType: 'FORM_46',
    notificationDate: '2025-06-24 17:37:16',
    processingDate: '2025-06-25 16:24:01',
    status: 'transformation_failed',
    correctedOn: '',
  },
  {
    id: '2',
    batchId: 'AP_LR_REQUEST_20250624193716',
    fileId: 'AP-M-2025-7354',
    aripoSequence: '186678-13',
    fileSequence: '13',
    formType: 'FORM_M8',
    notificationDate: '2025-06-24 17:37:16',
    processingDate: '2025-06-25 16:24:01',
    status: 'transformation_failed',
    correctedOn: '',
  },
  {
    id: '3',
    batchId: 'AP_LR_REQUEST_20250624193716',
    fileId: 'AP-P-2022-16567',
    aripoSequence: '186669-14',
    fileSequence: '14',
    formType: 'FORM_13',
    notificationDate: '2025-06-24 17:37:16',
    processingDate: '2025-06-25 16:24:01',
    status: 'transformation_failed',
    correctedOn: '',
  },
  {
    id: '4',
    batchId: 'AP_LR_REQUEST_20250617193811',
    fileId: 'AP-P-2025-16355',
    aripoSequence: '186467-13',
    fileSequence: '13',
    formType: 'FORM_13',
    notificationDate: '2025-06-17 17:38:11',
    processingDate: '2025-06-24 23:00:14',
    status: 'transformation_failed',
    correctedOn: '',
  },
  {
    id: '5',
    batchId: 'AP_LR_REQUEST_20250617193811',
    fileId: 'AP-P-2022-16363',
    aripoSequence: '186465-14',
    fileSequence: '14',
    formType: 'FORM_13',
    notificationDate: '2025-06-17 17:38:11',
    processingDate: '2025-06-24 23:00:14',
    status: 'transformation_failed',
    correctedOn: '',
  },
  {
    id: '6',
    batchId: 'AP_LR_REQUEST_20250617193811',
    fileId: 'AP-P-2022-16349',
    aripoSequence: '186469-14',
    fileSequence: '14',
    formType: 'FORM_13',
    notificationDate: '2025-06-17 17:38:11',
    processingDate: '2025-06-24 23:00:14',
    status: 'transformation_failed',
    correctedOn: '',
  },
];

export const aripoOutgoingNotificationsData = [
  {
    id: '1',
    batchId: 'AP_LR_REQUEST_20250624193716',
    fileId: 'AP-P-2022-14476',
    aripoSequence: '186660-14',
    fileSequence: '14',
    formType: 'FORM_46',
    notificationDate: '2025-06-24 17:37:16',
    receivedDate: '2025-06-25 16:24:01',
    status: 'Granted',
    correctedOn: '',
  },
  {
    id: '2',
    batchId: 'AP_LR_REQUEST_20250624193716',
    fileId: 'AP-M-2025-7354',
    aripoSequence: '186678-13',
    fileSequence: '13',
    formType: 'FORM_M8',
    notificationDate: '2025-06-24 17:37:16',
    receivedDate: '2025-06-25 16:24:01',
    status: 'Granted',
    correctedOn: '',
  },
  {
    id: '3',
    batchId: 'AP_LR_REQUEST_20250624193716',
    fileId: 'AP-P-2022-16567',
    aripoSequence: '186669-14',
    fileSequence: '14',
    formType: 'FORM_13',
    notificationDate: '2025-06-24 17:37:16',
    receivedDate: '2025-06-25 16:24:01',
    status: 'Refused',
    correctedOn: '',
  },
  {
    id: '4',
    batchId: 'AP_LR_REQUEST_20250617193811',
    fileId: 'AP-P-2025-16355',
    aripoSequence: '186467-13',
    fileSequence: '13',
    formType: 'FORM_13',
    notificationDate: '2025-06-17 17:38:11',
    receivedDate: '2025-06-24 23:00:14',
    status: 'Refused',
    correctedOn: '',
  },
  {
    id: '5',
    batchId: 'AP_LR_REQUEST_20250617193811',
    fileId: 'AP-P-2022-16363',
    aripoSequence: '186465-14',
    fileSequence: '14',
    formType: 'FORM_13',
    notificationDate: '2025-06-17 17:38:11',
    receivedDate: '2025-06-24 23:00:14',
    status: 'Granted',
    correctedOn: '',
  },
  {
    id: '6',
    batchId: 'AP_LR_REQUEST_20250617193811',
    fileId: 'AP-P-2022-16349',
    aripoSequence: '186469-14',
    fileSequence: '14',
    formType: 'FORM_13',
    notificationDate: '2025-06-17 17:38:11',
    receivedDate: '2025-06-24 23:00:14',
    status: 'Granted',
    correctedOn: '',
  },
];

export const hagueIncomingNotificationData = [
  {
    id: '1',
    bulletin: '1',
    irn: '12/2024',
    transaction: 'Cleaning',
    notifiedDate: '2024-12-01',
    importedDate: '2024-12-02',
    status: 'Success',
  },
  {
    id: '2',
    bulletin: '11',
    irn: '01/2025',
    transaction: 'Cleaning',
    notifiedDate: '2025-01-19',
    importedDate: '2025-01-19',
    status: 'Success',
  },
  {
    id: '3',
    bulletin: '13',
    irn: '02/2025',
    transaction: 'Cleaning',
    notifiedDate: '2025-07-22',
    importedDate: '2025-07-23',
    status: 'Success',
  },
  {
    id: '4',
    bulletin: '33',
    irn: '02/2025',
    transaction: 'Machine',
    notifiedDate: '2024-07-22',
    importedDate: '2024-07-23',
    status: 'Error',
  },
  {
    id: '5',
    bulletin: '33',
    irn: '02/2025',
    transaction: 'Machine',
    notifiedDate: '2024-12-01',
    importedDate: '2024-12-02',
    status: 'Success',
  },
  {
    id: '6',
    bulletin: '31',
    irn: '02/2025',
    transaction: 'Cleaning',
    notifiedDate: '2024-02-11',
    importedDate: '2024-02-14',
    status: 'Error',
  },
];

export const hagueOutgoingNotificationData = [
  {
    id: '1',
    irn: '12/2024',
    transaction: 'Cleaning',
    responsibleUser: 'Joe Clark',
    lastAction: 'Accepted',
    notifiedDate: '2024-12-01',
    recordedDate: '2024-12-02',
    sentDate: '2024-12-03',
    decision: 'Granted',
  },
  {
    id: '2',
    irn: '01/2025',
    transaction: 'Cleaning',
    responsibleUser: 'David Boon',
    lastAction: 'Accepted',
    notifiedDate: '2025-01-19',
    recordedDate: '2025-01-19',
    sentDate: '2025-01-29',
    decision: 'Granted',
  },
  {
    id: '3',
    irn: '02/2025',
    transaction: 'Cleaning',
    responsibleUser: 'Peter Parker',
    lastAction: 'Accepted',
    notifiedDate: '2025-07-22',
    recordedDate: '2025-07-23',
    sentDate: '2025-08-03',
    decision: 'Granted',
  },
  {
    id: '4',
    irn: '02/2025',
    transaction: 'Machine',
    responsibleUser: 'Joe Clark',
    lastAction: 'Rejected',
    notifiedDate: '2024-07-22',
    recordedDate: '2024-07-23',
    sentDate: '2024-12-03',
    decision: 'Final_Refusal',
  },
  {
    id: '5',
    irn: '02/2025',
    transaction: 'Machine',
    responsibleUser: 'Peter Parker',
    lastAction: 'Accepted',
    notifiedDate: '2024-12-01',
    recordedDate: '2024-12-02',
    sentDate: '2024-12-03',
    decision: 'Granted',
  },
  {
    id: '6',
    irn: '02/2025',
    transaction: 'Cleaning',
    responsibleUser: 'Joe Clark',
    lastAction: 'Accepted',
    notifiedDate: '2024-02-11',
    recordedDate: '2024-02-14',
    sentDate: '2024-04-23',
    decision: 'Provisional_Refusal',
  },
];

export const madridIncomingNotificationData = [
  {
    id: '1',
    gazette: '46/2008',
    irn: '982424',
    transaction: 'BIRTH-ENN',
    notifiedDate: '2008-11-27',
    importedDate: '2025-01-27',
    status: 'Success',
    correctionRequired: 'true',
    correctedDate: '2024-12-16',
  },
  {
    id: '2',
    gazette: '16/2010',
    irn: '976891',
    transaction: 'DEATH-CPN',
    notifiedDate: '2008-05-07',
    importedDate: '2025-01-27',
    status: 'Error',
    correctionRequired: 'false',
    correctedDate: '',
  },
  {
    id: '3',
    gazette: '24/2018',
    irn: '976891',
    transaction: 'PROLONG-REN',
    notifiedDate: '2018-06-12',
    importedDate: '2025-01-27',
    status: 'Success',
    correctionRequired: 'false',
    correctedDate: '',
  },
  {
    id: '4',
    gazette: '39/2008',
    irn: '976891',
    transaction: 'BIRTH-ENN',
    notifiedDate: '2008-10-09',
    importedDate: '2025-01-27',
    status: 'Error',
    correctionRequired: 'false',
    correctedDate: '',
  },
  {
    id: '5',
    gazette: '45/2015',
    irn: '644785',
    transaction: 'PROLONG-REN',
    notifiedDate: '2015-11-17',
    importedDate: '2025-01-27',
    status: 'Error',
    correctionRequired: 'false',
    correctedDate: '',
  },
  {
    id: '6',
    gazette: '11/2011',
    irn: '1069699',
    transaction: 'BIRTH-ENN',
    notifiedDate: '2011-03-31',
    importedDate: '2024-09-06',
    status: 'Error',
    correctionRequired: 'false',
    correctedDate: '',
  },
];

export const madridOutgoingNotificationData = [
  {
    id: '1',
    irn: '982424',
    transaction: 'BIRTH-ENN',
    notifiedDate: '2008-11-27',
    dueDate: '2025-01-27',
    responsibleUser: 'Joe Clark',
    lastAction: 'Recorded',
    recordedDate: '2025-11-10',
    decision: 'Granted',
    sentDate: '2025-01-27',
  },
  {
    id: '2',
    irn: '976891',
    transaction: 'DEATH-CPN',
    notifiedDate: '2008-05-07',
    dueDate: '2024-12-27',
    responsibleUser: 'Steve Smith',
    lastAction: 'Recorded',
    recordedDate: '2024-08-12',
    decision: 'Final_Refusal',
    sentDate: '2025-01-27',
  },
  {
    id: '3',
    irn: '976891',
    transaction: 'PROLONG-REN',
    notifiedDate: '2018-06-12',
    dueDate: '2025-11-27',
    responsibleUser: 'Joe Clark',
    lastAction: 'Recorded',
    recordedDate: '2024-11-10',
    decision: 'Granted',
    sentDate: '2024-12-15',
  },
  {
    id: '4',
    irn: '976891',
    transaction: 'BIRTH-ENN',
    notifiedDate: '2008-10-09',
    dueDate: '2025-01-27',
    responsibleUser: 'Mark Smith',
    lastAction: 'Recorded',
    recordedDate: '2024-10-08',
    decision: 'Provisional_Refusal',
    sentDate: '2024-11-17',
  },
  {
    id: '5',
    irn: '644785',
    transaction: 'PROLONG-REN',
    notifiedDate: '2015-11-17',
    dueDate: '2024-12-27',
    responsibleUser: 'Peter Parker',
    lastAction: 'Recorded',
    recordedDate: '2024-11-10',
    decision: 'Granted',
    sentDate: '2025-01-27',
  },
  {
    id: '6',
    irn: '1069699',
    transaction: 'BIRTH-ENN',
    notifiedDate: '2011-03-31',
    dueDate: '2025-01-27',
    responsibleUser: 'Peter Parker',
    lastAction: 'Recorded',
    recordedDate: '2025-08-10',
    decision: 'Final_Refusal',
    sentDate: '2025-01-17',
  },
];

export const officeNotificationsData = [
  {
    id: '1',
    category: 'trademarks',
    documentName: 'Tea Bag',
    documentId: 'DOC_20250624_12',
    fileId: 'AP-T-2022-14476',
    printedDate: '2025-04-12',
    approvedDate: '2025-06-24',
    method: 'paper',
    responsibleUser: 'Joe Clark',
    stage: 'Approved',
    acknowledgeDate: '',
  },
  {
    id: '2',
    category: 'trademarks',
    documentName: 'Machine',
    documentId: 'DOC_20250624_22',
    fileId: 'AP-T-2022-28883',
    printedDate: '2024-12-11',
    approvedDate: '2025-06-24',
    method: 'email',
    responsibleUser: 'Peter Parker',
    stage: 'Acknowledged',
    acknowledgeDate: '2025-08-12',
  },
  {
    id: '3',
    category: 'trademarks',
    documentName: 'Material',
    documentId: 'DOC_20250412_33',
    fileId: 'AP-T-2024-11124',
    printedDate: '2025-01-03',
    approvedDate: '2025-04-12',
    method: 'online',
    responsibleUser: 'Joe Clark',
    stage: 'Approved',
    acknowledgeDate: '',
  },
  {
    id: '4',
    category: 'designs',
    documentName: 'Machine',
    documentId: 'DOC_20040828_11',
    fileId: 'AP-D-2002-00821',
    printedDate: '2004-01-12',
    approvedDate: '',
    method: 'paper',
    responsibleUser: 'Ben Cooper',
    stage: '',
    acknowledgeDate: '',
  },
  {
    id: '5',
    category: 'designs',
    documentName: 'Engine',
    documentId: 'DOC_20211102_2',
    fileId: 'AP-D-2021-12331',
    printedDate: '2025-04-12',
    approvedDate: '2025-06-24',
    method: 'email',
    responsibleUser: 'Joe Clark',
    stage: 'Approved',
    acknowledgeDate: '',
  },
  {
    id: '6',
    category: 'patents',
    documentName: 'Air Flyer',
    documentId: 'DOC_20240814_11',
    fileId: 'AP-P-2024-11426',
    printedDate: '2024-02-16',
    approvedDate: '2024-08-24',
    method: 'paper',
    responsibleUser: 'Peter Parker',
    stage: 'Approved',
    acknowledgeDate: '',
  },
  {
    id: '7',
    category: 'patents',
    documentName: 'Machine',
    documentId: 'DOC_20250314_12',
    fileId: 'AP-P-2024-17876',
    printedDate: '2025-04-12',
    approvedDate: '2025-06-24',
    method: 'email',
    responsibleUser: 'Ben Cooper',
    stage: '',
    acknowledgeDate: '',
  },
  {
    id: '8',
    category: 'patents',
    documentName: 'Engine',
    documentId: 'DOC_20251224_44',
    fileId: 'AP-P-2025-22986',
    printedDate: '2025-01-22',
    approvedDate: '2025-06-24',
    method: 'online',
    responsibleUser: 'Peter Parker',
    stage: 'Approved',
    acknowledgeDate: '',
  },
  {
    id: '9',
    category: 'copyright',
    documentName: 'Machine',
    documentId: 'COPYRIGHT_1234421',
    fileId: 'AP-P-2022-14476',
    printedDate: '2024-01-02',
    approvedDate: '2024-06-24',
    method: 'email',
    responsibleUser: 'Joe Clark',
    stage: 'Approved',
    acknowledgeDate: '',
  },
  {
    id: '10',
    category: 'gi',
    documentName: 'Sony',
    documentId: 'GI_20250812_1',
    fileId: 'GI-202',
    printedDate: '2025-08-12',
    approvedDate: '2025-08-24',
    method: 'email',
    responsibleUser: 'Joe Clark',
    stage: 'Approved',
    acknowledgeDate: '',
  },
  {
    id: '11',
    category: 'post-filing',
    documentName: 'Filed',
    documentId: 'DOC_20250624_12',
    fileId: 'AP-P-2022-14476',
    printedDate: '2025-04-12',
    approvedDate: '2025-06-24',
    method: 'paper',
    responsibleUser: 'Joe Clark',
    stage: 'Approved',
    acknowledgeDate: '',
  },
  {
    id: '12',
    category: 'office-documents',
    documentName: 'Birth Date Change',
    documentId: 'DOC_20250624_14',
    fileId: 'AP-P-2022-14476',
    printedDate: '2025-04-12',
    approvedDate: '2025-06-24',
    method: 'paper',
    responsibleUser: 'Joe Clark',
    stage: 'Approved',
    acknowledgeDate: '',
  },
  {
    id: '13',
    category: 'office-documents',
    documentName: 'Address Change',
    documentId: 'DOC_20250624_12',
    fileId: 'AP-P-2022-14476',
    printedDate: '2025-04-12',
    approvedDate: '2025-06-24',
    method: 'paper',
    responsibleUser: 'Joe Clark',
    stage: 'Approved',
    acknowledgeDate: '',
  },
  {
    id: '14',
    category: 'others',
    documentName: 'Others',
    documentId: 'DOC_20250624_12',
    fileId: 'AP-P-2022-14476',
    printedDate: '2025-04-12',
    approvedDate: '2025-06-24',
    method: 'paper',
    responsibleUser: 'Ben Cooper',
    stage: 'Approved',
    acknowledgeDate: '',
  },
];

export const dataCaptureData = [
  {
    id: '1',
    category: 'trademarks',
    documentName: 'Tea Bag',
    documentId: 'DOC_20250624_12',
    fileId: 'AP-T-2022-14476',
    receivedDate: '2025-04-12',
    certifiedDate: '2025-06-24',
    certifiedBy: 'Joe Clark',
    stage: 'Digitalized',
    digitalizedDate: '2025-08-12',
    digitalizedBy: 'Ben Cooper',
  },
  {
    id: '2',
    category: 'trademarks',
    documentName: 'Machine',
    documentId: 'DOC_20250624_22',
    fileId: 'AP-T-2022-28883',
    receivedDate: '2024-12-11',
    certifiedDate: '2025-06-24',
    certifiedBy: 'Peter Parker',
    stage: 'Digitalized',
    digitalizedDate: '2025-08-12',
    digitalizedBy: 'Ben Cooper',
  },
  {
    id: '3',
    category: 'trademarks',
    documentName: 'Material',
    documentId: 'DOC_20250412_33',
    fileId: 'AP-T-2024-11124',
    receivedDate: '2025-01-03',
    certifiedDate: '2025-04-12',
    certifiedBy: 'Joe Clark',
    stage: 'Certified',
    digitalizedDate: '',
    digitalizedBy: '',
  },
  {
    id: '4',
    category: 'designs',
    documentName: 'Machine',
    documentId: 'DOC_20040828_11',
    fileId: 'AP-D-2002-00821',
    receivedDate: '2004-01-12',
    certifiedDate: '',
    certifiedBy: '',
    stage: 'Received',
    digitalizedDate: '',
    digitalizedBy: '',
  },
  {
    id: '5',
    category: 'designs',
    documentName: 'Engine',
    documentId: 'DOC_20211102_2',
    fileId: 'AP-D-2021-12331',
    receivedDate: '2025-04-12',
    certifiedDate: '2025-06-24',
    certifiedBy: 'Joe Clark',
    stage: 'Certified',
    digitalizedDate: '',
    digitalizedBy: '',
  },
  {
    id: '6',
    category: 'patents',
    documentName: 'Air Flyer',
    documentId: 'DOC_20240814_11',
    fileId: 'AP-P-2024-11426',
    receivedDate: '2024-02-16',
    certifiedDate: '2024-08-24',
    certifiedBy: 'Peter Parker',
    stage: 'Certified',
    digitalizedDate: '',
    digitalizedBy: '',
  },
  {
    id: '7',
    category: 'patents',
    documentName: 'Machine',
    documentId: 'DOC_20250314_12',
    fileId: 'AP-P-2024-17876',
    receivedDate: '2025-04-12',
    certifiedDate: '2025-06-24',
    certifiedBy: 'Ben Cooper',
    stage: 'Certified',
    digitalizedDate: '',
    digitalizedBy: '',
  },
  {
    id: '8',
    category: 'patents',
    documentName: 'Engine',
    documentId: 'DOC_20251224_44',
    fileId: 'AP-P-2025-22986',
    receivedDate: '2025-01-22',
    certifiedDate: '',
    certifiedBy: '',
    stage: 'Received',
    digitalizedDate: '',
    digitalizedBy: '',
  },
  {
    id: '9',
    category: 'copyright',
    documentName: 'Machine',
    documentId: 'COPYRIGHT_1234421',
    fileId: 'AP-P-2022-14476',
    receivedDate: '2024-01-02',
    certifiedDate: '2024-06-24',
    certifiedBy: 'Joe Clark',
    stage: 'Certified',
    digitalizedDate: '',
    digitalizedBy: '',
  },
  {
    id: '10',
    category: 'gi',
    documentName: 'Sony',
    documentId: 'GI_20250812_1',
    fileId: 'GI-202',
    receivedDate: '2025-08-12',
    certifiedDate: '2025-08-24',
    certifiedBy: 'Joe Clark',
    stage: 'Certified',
    digitalizedDate: '',
    digitalizedBy: '',
  },
  {
    id: '11',
    category: 'post-filing',
    documentName: 'Filed',
    documentId: 'DOC_20250624_12',
    fileId: 'AP-P-2022-14476',
    receivedDate: '2025-04-12',
    certifiedDate: '2025-06-24',
    certifiedBy: 'Joe Clark',
    stage: 'Certified',
    digitalizedDate: '',
    digitalizedBy: '',
  },
  {
    id: '12',
    category: 'others',
    documentName: 'Others',
    documentId: 'DOC_20250624_12',
    fileId: 'AP-P-2022-14476',
    receivedDate: '2025-04-12',
    certifiedDate: '2025-06-24',
    certifiedBy: 'Ben Cooper',
    stage: 'Certified',
    digitalizedDate: '',
    digitalizedBy: '',
  },
];

export const acknowledgeNotificationsData = [
  {
    id: '1',
    documentId: 'DOC_20250624_12',
    fileId: 'AP-P-2022-14476',
    transmissionDate: '2025-06-24',
    acknowledgeDate: '',
  },
  {
    id: '2',
    documentId: 'DOC_20250623_11',
    fileId: 'AP-P-2025-17601',
    transmissionDate: '2025-06-23',
    acknowledgeDate: '',
  },
  {
    id: '3',
    documentId: 'DOC_20250622_21',
    fileId: 'AP-P-2024-24761',
    transmissionDate: '2025-06-22',
    acknowledgeDate: '',
  },
];

export const queryTemplatesFromDb = [
  {
    templateId: '1',
    category: 'patents',
    title: 'Patent Search - US Filed',
    description: 'Common search for US filed patents with specific status',
    created: '2025-10-10',
    lastUsed: '2025-10-12',
    query: {
      category: 'patents',
      levelList: [
        {
          level: '1',
          levelId: '1',
          level_name: '',
          group_list: [
            {
              group: '1',
              group_name: 'Filter Group 1',
              file_list: [
                {
                  fieldId: '1',
                  field: { name: 'Description', code: 'DESC' },
                  connecting: { code: 'Like', name: 'Contains Word' },
                  value: 'cola',
                  operator: 'AND',
                  orOperator: false,
                },
                {
                  fieldId: '2',
                  field: { name: 'Nice', code: 'NCL' },
                  connecting: { code: 'Exact', name: 'Equals' },
                  value: '24',
                  operator: 'AND',
                  orOperator: false,
                },
              ],
              group_operator: 'AND',
              orOperator: false,
            },
          ],
          level_operator: 'AND',
          orOperator: false,
        },
        {
          level: '2',
          levelId: '2',
          level_name: 'Level 2 Query',
          group_list: [
            {
              group: '2',
              group_name: 'Filter Group 2',
              file_list: [
                {
                  fieldId: '1',
                  field: { name: 'Applicant County', code: 'APCT' },
                  connecting: { code: 'Exact', name: 'Equals' },
                  value: 'VC',
                  operator: 'AND',
                  orOperator: false,
                },
                {
                  fieldId: '2',
                  field: { name: 'Vienna', code: 'VCL' },
                  connecting: { code: 'Starts', name: 'Starts With' },
                  value: '1.13',
                  operator: 'AND',
                  orOperator: false,
                },
              ],
              group_operator: 'AND',
              orOperator: false,
            },
            {
              group: '3',
              group_name: 'Filter Group 3',
              file_list: [
                {
                  fieldId: '3',
                  field: { name: 'Mark Name', code: 'MK' },
                  connecting: { code: 'Like', name: 'Contains Word' },
                  value: '3D',
                  operator: 'AND',
                  orOperator: false,
                },
                {
                  fieldId: '4',
                  field: { name: 'Application Type', code: 'APP_TYP' },
                  connecting: { code: 'Like', name: 'Contains Word' },
                  value: 'premium',
                  operator: 'AND',
                  orOperator: false,
                },
              ],
              group_operator: 'AND',
              orOperator: false,
            },
          ],
          level_operator: 'OR',
          orOperator: true,
        },
        {
          level: '1',
          levelId: '3',
          level_name: '',
          group_list: [
            {
              group: '4',
              group_name: 'Filter Group 4',
              file_list: [
                {
                  fieldId: '1',
                  field: { name: 'Status', code: 'STLB' },
                  connecting: { code: 'Exact', name: 'Equals' },
                  value: 'Registered',
                  operator: 'AND',
                  orOperator: false,
                },
              ],
              group_operator: 'AND',
              orOperator: false,
            },
          ],
          level_operator: 'AND',
          orOperator: false,
        },
      ],
    },
  },
  {
    templateId: '2',
    category: 'trademarks',
    title: 'Trademark Brand Search',
    description: 'Search for trademark brand names and goods/services',
    created: '2025-10-10',
    lastUsed: '2025-10-12',
    query: {
      category: 'patents',
      levelList: [
        {
          level: '1',
          levelId: '1',
          level_name: '',
          group_list: [
            {
              group: '1',
              group_name: 'Filter Group 1',
              file_list: [
                {
                  fieldId: '1',
                  field: { name: 'Description', code: 'DESC' },
                  connecting: { code: 'Like', name: 'Contains Word' },
                  value: 'cola',
                  operator: 'AND',
                  orOperator: false,
                },
                {
                  fieldId: '2',
                  field: { name: 'Nice', code: 'NCL' },
                  connecting: { code: 'Exact', name: 'Equals' },
                  value: '24',
                  operator: 'AND',
                  orOperator: false,
                },
              ],
              group_operator: 'AND',
              orOperator: false,
            },
          ],
          level_operator: 'AND',
          orOperator: false,
        },
        {
          level: '2',
          levelId: '2',
          level_name: 'Level 2 Query',
          group_list: [
            {
              group: '2',
              group_name: 'Filter Group 2',
              file_list: [
                {
                  fieldId: '1',
                  field: { name: 'Applicant County', code: 'APCT' },
                  connecting: { code: 'Exact', name: 'Equals' },
                  value: 'VC',
                  operator: 'AND',
                  orOperator: false,
                },
                {
                  fieldId: '2',
                  field: { name: 'Vienna', code: 'VCL' },
                  connecting: { code: 'Starts', name: 'Starts With' },
                  value: '1.13',
                  operator: 'AND',
                  orOperator: false,
                },
              ],
              group_operator: 'AND',
              orOperator: false,
            },
            {
              group: '3',
              group_name: 'Filter Group 3',
              file_list: [
                {
                  fieldId: '3',
                  field: { name: 'Mark Name', code: 'MK' },
                  connecting: { code: 'Like', name: 'Contains Word' },
                  value: '3D',
                  operator: 'AND',
                  orOperator: false,
                },
                {
                  fieldId: '4',
                  field: { name: 'Application Type', code: 'APP_TYP' },
                  connecting: { code: 'Like', name: 'Contains Word' },
                  value: 'premium',
                  operator: 'AND',
                  orOperator: false,
                },
              ],
              group_operator: 'AND',
              orOperator: false,
            },
          ],
          level_operator: 'OR',
          orOperator: true,
        },
        {
          level: '1',
          levelId: '3',
          level_name: '',
          group_list: [
            {
              group: '4',
              group_name: 'Filter Group 4',
              file_list: [
                {
                  fieldId: '1',
                  field: { name: 'Status', code: 'STLB' },
                  connecting: { code: 'Exact', name: 'Equals' },
                  value: 'Registered',
                  operator: 'AND',
                  orOperator: false,
                },
              ],
              group_operator: 'AND',
              orOperator: false,
            },
          ],
          level_operator: 'AND',
          orOperator: false,
        },
      ],
    },
  },
  {
    templateId: '3',
    category: 'authorityfiles',
    title: 'Authority Files Sample',
    description: 'Search for Authority files related queries',
    created: '2025-10-10',
    lastUsed: '2025-10-12',
    query: {
      category: 'patents',
      levelList: [
        {
          level: '1',
          levelId: '1',
          level_name: '',
          group_list: [
            {
              group: '1',
              group_name: 'Filter Group 1',
              file_list: [
                {
                  fieldId: '1',
                  field: { name: 'Description', code: 'DESC' },
                  connecting: { code: 'Like', name: 'Contains Word' },
                  value: 'cola',
                  operator: 'AND',
                  orOperator: false,
                },
                {
                  fieldId: '2',
                  field: { name: 'Nice', code: 'NCL' },
                  connecting: { code: 'Exact', name: 'Equals' },
                  value: '24',
                  operator: 'AND',
                  orOperator: false,
                },
              ],
              group_operator: 'AND',
              orOperator: false,
            },
          ],
          level_operator: 'AND',
          orOperator: false,
        },
        {
          level: '2',
          levelId: '2',
          level_name: 'Level 2 Query',
          group_list: [
            {
              group: '2',
              group_name: 'Filter Group 2',
              file_list: [
                {
                  fieldId: '1',
                  field: { name: 'Applicant County', code: 'APCT' },
                  connecting: { code: 'Exact', name: 'Equals' },
                  value: 'VC',
                  operator: 'AND',
                  orOperator: false,
                },
                {
                  fieldId: '2',
                  field: { name: 'Vienna', code: 'VCL' },
                  connecting: { code: 'Starts', name: 'Starts With' },
                  value: '1.13',
                  operator: 'AND',
                  orOperator: false,
                },
              ],
              group_operator: 'AND',
              orOperator: false,
            },
            {
              group: '3',
              group_name: 'Filter Group 3',
              file_list: [
                {
                  fieldId: '3',
                  field: { name: 'Mark Name', code: 'MK' },
                  connecting: { code: 'Like', name: 'Contains Word' },
                  value: '3D',
                  operator: 'AND',
                  orOperator: false,
                },
                {
                  fieldId: '4',
                  field: { name: 'Application Type', code: 'APP_TYP' },
                  connecting: { code: 'Like', name: 'Contains Word' },
                  value: 'premium',
                  operator: 'AND',
                  orOperator: false,
                },
              ],
              group_operator: 'AND',
              orOperator: false,
            },
          ],
          level_operator: 'OR',
          orOperator: true,
        },
        {
          level: '1',
          levelId: '3',
          level_name: '',
          group_list: [
            {
              group: '4',
              group_name: 'Filter Group 4',
              file_list: [
                {
                  fieldId: '1',
                  field: { name: 'Status', code: 'STLB' },
                  connecting: { code: 'Exact', name: 'Equals' },
                  value: 'Registered',
                  operator: 'AND',
                  orOperator: false,
                },
              ],
              group_operator: 'AND',
              orOperator: false,
            },
          ],
          level_operator: 'AND',
          orOperator: false,
        },
      ],
    },
  },
];

export const mockActionProcesses = [
  {
    processId: 'user_doc_sample',
    processName: 'User Doc Sample',
    actions: [
      { actionId: 'all_processes', actionName: 'All Processes' },
      { actionId: 'business_processes', actionName: 'Business Processes' },
    ],
  },
  {
    processId: 'action_state',
    processName: 'Action State',
    actions: [
      {
        actionId: 'ah_absolute_acceptance',
        actionName: 'AH Absolute Acceptance following PM',
      },
    ],
  },
];
